[package]
name = "lebrs"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.5.1"
candle-nn = "0.5.1"
csv = { version = "1.3.0" }
polars = { version = "0.40.0", features = ["lazy", "json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

